### ISSUE TITLE
No vendor folder found.

### ISSUE THREAD

**Issue by calendarbase** [MitocGroup/deep-microservices-todomvc#109]
Strange issue:

19:56:25 GMT+0100 (CET)  Request /deep-todomvc/js/vendor/github/angular/bower-angular@1.5.7.js -> /deep-todomvc/js/vendor/github/angular/bower-angular@1.5.7.js 
19:56:25 GMT+0100 (CET)  File /Users/nissegrankvist/Documents/E-Commerce/deep-microservices-todomvc/deep-todomvc/frontend/js/vendor/github/angular/bower-angular@1.5.7.js not found 

There is no vendor folder.

Should the folder structure look like this:
/deep-microservices-todomvc/
   /deep-todomvc/
   /deep-root-angular/
   deeploy.json

I got this installation error:

$ deepify server ~/deep-microservices-todomvc -o
Do you want to specify parameters values? (Y/N): N
20:39:48 GMT+0100 (CET)  learn.json was successfully copied into deep-root-angular 
Installing latest deep-framework from GitHub
20:39:48 GMT+0100 (CET)  Error while installing frontend dependencies { Error: Command failed: jspm install
/bin/sh: jspm: command not found

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:493:12) killed: false, code: 127, signal: null, cmd: 'jspm install' } 
20:39:48 GMT+0100 (CET)  Frontend dependencies have been intalled for deep-todomvc

**Comment by eistrati** [comment]
@calendarbase Thanks for reporting this issue. We'll take a look at this issue and get back to you soon.

From what I see, `/deep-microservices-todomvc/` is not in the right place, which I would assume you've tried to `deepify install` again inside already installed `/Users/nissegrankvist/Documents/E-Commerce/deep-microservices-todomvc/`. You can safely remove it: `rm -rf /Users/nissegrankvist/Documents/E-Commerce/deep-microservices-todomvc/deep-microservices-todomvc/`

When you list installed todomvc application, it should look like this:

```shell
$ ls -al /Users/nissegrankvist/Documents/E-Commerce/deep-microservices-todomvc/deep-microservices-todomvc/

/deep-todomvc/
/deep-root-angular/
deeploy.json
```

For your reference, the structure of any (so called) `deep microservice` is the following:
```shell
/whatever-you-want-as-a-name/
    /backend/
    /data/
    /docs/
    /frontend/
    /tests/
```

I see that `https://github.com/MitocGroup/deep-microservices-todomvc/tree/dev/src/deep-todomvc/frontend/js/vendor/` is missing, so we'll check on our end and see why it's missing. Thanks again for pointing it out.

**Comment by AlexanderC** [comment]
@calendarbase as i see from your stack trace `jspm` binaries are missing(`/bin/sh: jspm: command not found`) so the dependencies failed to install. To fix the issue you have to install `jspm` (please refer to this page http://jspm.io/docs/getting-started.html) and rerun the desired command.

**Comment by calendarbase** [comment]
Installed jspm.

First as before I get the apVesrion is missing then I fix the deeploy file and got this:

16:46:00 GMT+0100 (CET)  DEEP registry is not available on https://deep.mg 
16:46:02 GMT+0100 (CET)  Module 'adtechmedia-website@*' installation failed: Error: 404 Not Found: https://raw.githubusercontent.com/AdTechMedia/adtechmedia-website/*/src/adtechmedia-website/deepkg.json 
16:46:02 GMT+0100 (CET)  { Error: 404 Not Found: https://raw.githubusercontent.com/AdTechMedia/adtechmedia-website/*/src/adtechmedia-website/deepkg.json
    at /Users/goransvensson/.npm-packages/lib/node_modules/deepify/node_modules/fetchy-request/index.js:39:27
    at process._tickDomainCallback (internal/process/next_tick.js:129:7)
  response: 
   IncomingMessage {
     _readableState: 
      ReadableState {
        objectMode: false,
        highWaterMark: 16384,
        buffer: [Object],
        length: 15,
        pipes: null,
        pipesCount: 0,
        flowing: null,
        ended: true,
        endEmitted: false,
        reading: false,
        sync: true,
        needReadable: false,
        emittedReadable: true,
        readableListening: false,
        resumeScheduled: false,
        defaultEncoding: 'utf8',
        ranOut: false,
        awaitDrain: 0,
        readingMore: true,
        decoder: null,
        encoding: null },
     readable: true,
     domain: null,
     _events: { end: [Function: responseOnEnd] },
     _eventsCount: 1,
     _maxListeners: undefined,
     socket: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: undefined,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'raw.githubusercontent.com',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 196,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true },
     connection: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: undefined,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'raw.githubusercontent.com',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 196,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true },
     httpVersionMajor: 1,
     httpVersionMinor: 1,
     httpVersion: '1.1',
     complete: true,
     headers: 
      { 'content-security-policy': 'default-src \'none\'; style-src \'unsafe-inline\'',
        'strict-transport-security': 'max-age=31536000',
        'x-content-type-options': 'nosniff',
        'x-frame-options': 'deny',
        'x-xss-protection': '1; mode=block',
        'x-github-request-id': '3764:2F8FD:58D4959:5B38A79:58A71AB9',
        'content-length': '15',
        'accept-ranges': 'bytes',
        date: 'Fri, 17 Feb 2017 15:46:02 GMT',
        via: '1.1 varnish',
        connection: 'close',
        'x-served-by': 'cache-bma7027-BMA',
        'x-cache': 'MISS',
        'x-cache-hits': '0',
        'x-timer': 'S1487346362.237473,VS0,VE128',
        vary: 'Authorization,Accept-Encoding',
        'access-control-allow-origin': '*',
        'x-fastly-request-id': '5a0ebaeafdfc0c6dc634c70f5f7f50616b0c72da',
        expires: 'Fri, 17 Feb 2017 15:51:02 GMT',
        'source-age': '0' },
     rawHeaders: 
      [ 'Content-Security-Policy',
        'default-src \'none\'; style-src \'unsafe-inline\'',
        'Strict-Transport-Security',
        'max-age=31536000',
        'X-Content-Type-Options',
        'nosniff',
        'X-Frame-Options',
        'deny',
        'X-XSS-Protection',
        '1; mode=block',
        'X-GitHub-Request-Id',
        '3764:2F8FD:58D4959:5B38A79:58A71AB9',
        'Content-Length',
        '15',
        'Accept-Ranges',
        'bytes',
        'Date',
        'Fri, 17 Feb 2017 15:46:02 GMT',
        'Via',
        '1.1 varnish',
        'Connection',
        'close',
        'X-Served-By',
        'cache-bma7027-BMA',
        'X-Cache',
        'MISS',
        'X-Cache-Hits',
        '0',
        'X-Timer',
        'S1487346362.237473,VS0,VE128',
        'Vary',
        'Authorization,Accept-Encoding',
        'Access-Control-Allow-Origin',
        '*',
        'X-Fastly-Request-ID',
        '5a0ebaeafdfc0c6dc634c70f5f7f50616b0c72da',
        'Expires',
        'Fri, 17 Feb 2017 15:51:02 GMT',
        'Source-Age',
        '0' ],
     trailers: {},
     rawTrailers: [],
     upgrade: false,
     url: '',
     method: null,
     statusCode: 404,
     statusMessage: 'Not Found',
     client: 
      TLSSocket {
        _tlsOptions: [Object],
        _secureEstablished: true,
        _securePending: false,
        _newSessionPending: false,
        _controlReleased: true,
        _SNICallback: null,
        servername: null,
        npnProtocol: undefined,
        alpnProtocol: false,
        authorized: true,
        authorizationError: null,
        encrypted: true,
        _events: [Object],
        _eventsCount: 10,
        connecting: false,
        _hadError: false,
        _handle: [Object],
        _parent: null,
        _host: 'raw.githubusercontent.com',
        _readableState: [Object],
        readable: true,
        domain: null,
        _maxListeners: undefined,
        _writableState: [Object],
        writable: true,
        allowHalfOpen: false,
        destroyed: false,
        _bytesDispatched: 196,
        _sockname: null,
        _pendingData: null,
        _pendingEncoding: '',
        server: undefined,
        _server: null,
        ssl: [Object],
        _requestCert: true,
        _rejectUnauthorized: true,
        parser: null,
        _httpMessage: [Object],
        read: [Function],
        _consuming: true },
     _consuming: false,
     _dumped: false,
     req: 
      ClientRequest {
        domain: null,
        _events: [Object],
        _eventsCount: 4,
        _maxListeners: undefined,
        output: [],
        outputEncodings: [],
        outputCallbacks: [],
        outputSize: 0,
        writable: true,
        _last: true,
        upgrading: false,
        chunkedEncoding: false,
        shouldKeepAlive: false,
        useChunkedEncodingByDefault: false,
        sendDate: false,
        _removedHeader: {},
        _contentLength: 0,
        _hasBody: true,
        _trailer: '',
        finished: true,
        _headerSent: true,
        socket: [Object],
        connection: [Object],
        _header: 'GET /AdTechMedia/adtechmedia-website/*/src/adtechmedia-website/deepkg.json HTTP/1.1\r\nAccept: */*\r\nUser-Agent: deep-registry-rq-1487346362084\r\nHost: raw.githubusercontent.com\r\nConnection: close\r\n\r\n',
        _headers: [Object],
        _headerNames: [Object],
        _onPendingData: null,
        agent: [Object],
        socketPath: undefined,
        method: 'GET',
        path: '/AdTechMedia/adtechmedia-website/*/src/adtechmedia-website/deepkg.json',
        _ended: false,
        parser: null,
        res: [Circular] },
     timing: 
      { start: 1487346362084,
        socket: 1487346362085,
        connect: 1487346362123,
        response: 1487346362403,
        abort: 0,
        error: 0 },
     uri: 'https://raw.githubusercontent.com/AdTechMedia/adtechmedia-website/*/src/adtechmedia-website/deepkg.json' },
  request: 
   { uri: 'https://raw.githubusercontent.com/AdTechMedia/adtechmedia-website/*/src/adtechmedia-website/deepkg.json',
     method: 'GET',
     headers: 
      { Accept: '*/*',
        'User-Agent': 'deep-registry-rq-1487346362084' },
     body: null,
     timeout: 0,
     keepAlive: undefined,
     retry: { retries: 0, minTimeout: 300, maxTimeout: 500 },
     displayName: 'https://raw.githubusercontent.com/AdTechMedia/adtechmedia-website/*/src/adtechmedia-website/deepkg.json',
     label: undefined } } 

I will try it in Ubuntu to see if it works there.

**Comment by calendarbase** [comment]
Tested again on OSX, this time with the hello-world example and it works. The missing vendor folders and files is installed.

Don't know why the adtech media site did not work, maybe an network issue.

**Comment by eistrati** [comment]
AdTechMedia website is an issue on our end. Thanks for reporting it!

We've fixed it and somebody on our team will merge it after it passes Travis and CodeClimate: https://github.com/AdTechMedia/adtechmedia-website/pull/61

I'll close this issue now and feel free to open new ones. Really appreciate your help!
