### ISSUE TITLE
Implement new deep-validation method for all lambdas

### ISSUE THREAD

**Issue by AScripnic** [MitocGroup/deep-microservices-todomvc#48]
Implement new deep-validation method for all lambdas based on last changes

**Comment by eistrati** [comment]
Please fix the following problems as well:
1. I can create empty tasks in todomvc
2. First show in UI that task was created and then "revert" if call to Lambda failed
3. Implement bundle.min.js
4. Reuse https://github.com/MitocGroup/deep-microservices-root-angular/issues/69
